Project Gistalk {
  database_type: 'PostgreSQL'
  Note: '''
    # Gistalk
    A database for storing the Gistalk project. 
    [Github](https://github.com/gsainfoteam/gistalk-be)
  '''
}

Enum Semester {
  SPRING
  SUMMER
  FALL
  WINTER
  ALL
}

Enum Recommendation {
  YES
  NO
  MAYBE
}

Table User {
  uuid uuid [pk]
  student_number int
  name varchar
  consent boolean
  created_at datetime
}

Table TakingLectures {
  user_uuid varchar [pk] [ref: > User.uuid]
  lecture_id int [ref: > Lecture.id]
}

Table Professor {
  id int [pk, increment]
  name varchar
}

Table LectureCode {
  code varchar [pk]

  lecture_id int [ref: > Lecture.id]
}

Table Lecture {
  id int [pk, increment]
  name varchar 
}

Table LectureProfessor {
  lecture_id int [ref: > Lecture.id]
  professor_id int [ref: > Professor.id]

  Indexes {
    (lecture_id, professor_id) [pk]
  }
}

Table WriteRecord {
  user_uuid varchar [ref: > User.uuid]
  record_id int [ref: > Record.id]
  lecture_id int [ref: > Lecture.id]

  Indexes {
    (user_uuid, record_id)
  }
}

Table Record {
  id int [pk, increment]

  difficulty int
  skill int
  helpfulness int
  interest int
  load int
  generosity int

  review varchar

  recommendation Recommendation
  semester Semester
  year int

  created_at datetime

  user_uuid uuid [ref: > User.uuid]
  lecture_id int [ref: > Lecture.id]
  professor_id int [ref: > Professor.id]
}
