name: Update Kubernetes Cluster (Dev)

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build docker Image
    runs-on: ubuntu-latest
    outputs:
      ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      ECR_REPOSITORY: gistlak-backend
      IMAGE_TAG: dev${{ github.run_number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          mask-aws-account-id: no

  deploy:
    name: Update Git Repository
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: gsainfoteam/icarus-gitops
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          fetch-depth: 0

      - name: Update Kubernetes Manifest
        env:
          ECR_REGISTRY: ${{ needs.build.outputs.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ needs.build.outputs.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ needs.build.outputs.IMAGE_TAG }}
        run: |
          sed -i "s|image:.*|image: $ECR_REGISTRY\/$ECR_REPOSITORY:$IMAGE_TAG|g" infoteam/service/gistalk/stg.yaml

      - name: Commit and Push
        env:
          ECR_REPOSITORY: ${{ needs.build.outputs.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ needs.build.outputs.IMAGE_TAG }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Update image $ECR_REPOSITORY:$IMAGE_TAG"
          git push -u origin master
